import { type CSSProperties } from "react";

export function flocon(hue: number) {
    return {
        dark: {
            "--accent": `${hue} 10% 90%`,
            "--accent-foreground": `${hue} 0% 4%`,
            "--background": `${hue} 12% 6%`,
            "--border": `${hue} 16% 16%`,
            "--card": `${hue} 12% 8%`,
            "--card-foreground": `${hue} 10% 90%`,
            "--foreground": `${hue} 3% 90%`,
            "--input": `${hue} 17% 20%`,
            "--muted": `${hue} 15% 13%`,
            "--muted-foreground": `${hue} 10% 75%`,
            "--popover": `${hue} 0% 100%`,
            "--popover-foreground": `${hue} 10% 10%`,
            "--primary": `${hue} 30% 67%`,
            "--primary-foreground": `${hue} 0% 100%`,
            "--ring": `${hue} 15% 90%`,
            "--secondary": `${hue} 17% 10%`,
            "--secondary-foreground": `${hue} 0% 100%`,
        } as CSSProperties,
        light: {
            "--accent": `${hue} 15% 90%`,
            "--accent-foreground": `${hue} 0% 15%`,
            "--background": `${hue} 41% 99%`,
            "--border": `${hue} 16% 77%`,
            "--card": `${hue} 5% 99%`,
            "--card-foreground": `${hue} 10% 17%`,
            "--foreground": `${hue} 3% 16%`,
            "--input": `${hue} 17% 77%`,
            "--muted": `${hue} 35% 94%`,
            "--muted-foreground": `${hue} 10% 35%`,
            "--popover": `${hue} 0% 100%`,
            "--popover-foreground": `${hue} 10% 10%`,
            "--primary": `${hue} 49% 62%`,
            "--primary-foreground": `${hue} 0% 100%`,
            "--ring": `${hue} 15% 32%`,
            "--secondary": `${hue} 37% 93%`,
            "--secondary-foreground": `${hue} 0% 15%`,
        } as CSSProperties,
    }
}

export function charm(hue: number) {
    return {
        dark: {
            "--accent": `${hue} 25% 14%`,
            "--accent-foreground": `${hue} 0% 98%`,
            "--background": `${hue} 12% 3%`,
            "--border": `${hue} 20% 9%`,
            "--card": `${hue} 15% 5%`,
            "--card-foreground": `${hue} 21% 97%`,
            "--foreground": `${hue} 17% 96%`,
            "--input": `${hue} 20% 13%`,
            "--muted": `${hue} 27% 15%`,
            "--muted-foreground": `${hue} 13% 64%`,
            "--popover": `${hue} 37% 3%`,
            "--popover-foreground": `${hue} 15% 98%`,
            "--primary": `${hue} 55% 87%`,
            "--primary-foreground": `${hue} 35% 10%`,
            "--ring": `${hue} 33% 83%`,
            "--secondary": `${hue} 16% 13%`,
            "--secondary-foreground": `${hue} 40% 95%`,
        } as CSSProperties,
        light: {
            "--accent": `${hue} 25% 92%`,
            "--accent-foreground": `${hue} 17% 7%`,
            "--background": `${hue} 29% 99%`,
            "--border": `${hue} 20% 92%`,
            "--card": `${hue} 15% 100%`,
            "--card-foreground": `${hue} 21% 7%`,
            "--foreground": `${hue} 17% 7%`,
            "--input": `${hue} 20% 92%`,
            "--muted": `${hue} 27% 90%`,
            "--muted-foreground": `${hue} 13% 30%`,
            "--popover": `${hue} 37% 90%`,
            "--popover-foreground": `${hue} 15% 5%`,
            "--primary": `${hue} 20% 20%`,
            "--primary-foreground": `${hue} 20% 96%`,
            "--ring": `${hue} 83% 3%`,
            "--secondary": `${hue} 16% 90%`,
            "--secondary-foreground": `${hue} 40% 5%`,
        } as CSSProperties,
    }
}

export function eclipse(hue: number) {
    return {
        dark: {
            "--accent": `${hue} 2% 17%`,
            "--accent-foreground": `${hue} 2% 100%`,
            "--background": `${hue} 2% 1%`,
            "--border": `${hue} 10% 23%`,
            "--card": `${hue} 15% 3%`,
            "--card-foreground": `${hue} 2% 100%`,
            "--foreground": `${hue} 2% 100%`,
            "--input": `${hue} 10% 23%`,
            "--muted": `${hue} 10% 8%`,
            "--muted-foreground": `${hue} 2% 52%`,
            "--popover": `${hue} 2% 1%`,
            "--popover-foreground": `${hue} 2% 100%`,
            "--primary": `${hue} 31% 92%`,
            "--primary-foreground": `${hue} 2% 0%`,
            "--ring": `${hue} 23% 90%`,
            "--secondary": `${hue} 8% 14%`,
            "--secondary-foreground": `${hue} 2% 100%`,
        } as CSSProperties,
        light: {
            "--accent": `${hue} 2% 88%`,
            "--accent-foreground": `${hue} 2% 0%`,
            "--background": `${hue} 22% 99%`,
            "--border": `${hue} 7% 62%`,
            "--card": `${hue} 2% 100%`,
            "--card-foreground": `${hue} 2% 0%`,
            "--foreground": `${hue} 2% 0%`,
            "--input": `${hue} 10% 60%`,
            "--muted": `${hue} 2% 93%`,
            "--muted-foreground": `${hue} 2% 49%`,
            "--popover": `${hue} 2% 99%`,
            "--popover-foreground": `${hue} 2% 0%`,
            "--primary": `${hue} 32% 9%`,
            "--primary-foreground": `${hue} 2% 100%`,
            "--ring": `${hue} 71% 11%`,
            "--secondary": `${hue} 30% 92%`,
            "--secondary-foreground": `${hue} 30% 9%`,
        } as CSSProperties,
    }
}

export function oasis(hue: number) {
    return {
        dark: {
            "--accent": `${hue} 12% 24%`,
            "--accent-foreground": `${hue} 10% 95%`,
            "--background": `${hue} 10% 4%`,
            "--border": `${hue} 10% 16%`,
            "--card": `${hue} 12% 8%`,
            "--card-foreground": `${hue} 8% 96%`,
            "--foreground": `${hue} 8% 90%`,
            "--input": `${hue} 10% 16%`,
            "--muted": `${hue} 16% 9%`,
            "--muted-foreground": `${hue} 14% 56%`,
            "--popover": `${hue} 5% 10%`,
            "--popover-foreground": `${hue} 8% 98%`,
            "--primary": `${hue} 10% 80%`,
            "--primary-foreground": `${hue} 0% 96%`,
            "--ring": `${hue} 21% 17%`,
            "--secondary": `${hue} 12% 10%`,
            "--secondary-foreground": `${hue} 28% 90%`,
        } as CSSProperties,
        light: {
            "--accent": `${hue} 12% 88%`,
            "--accent-foreground": `${hue} 10% 14%`,
            "--background": `${hue} 10% 97%`,
            "--border": `${hue} 26% 87%`,
            "--card": `${hue} 15% 99%`,
            "--card-foreground": `${hue} 8% 15%`,
            "--foreground": `${hue} 8% 15%`,
            "--input": `${hue} 26% 87%`,
            "--muted": `${hue} 16% 87%`,
            "--muted-foreground": `${hue} 14% 56%`,
            "--popover": `${hue} 5% 99%`,
            "--popover-foreground": `${hue} 8% 10%`,
            "--primary": `${hue} 10% 37%`,
            "--primary-foreground": `${hue} 0% 96%`,
            "--ring": `${hue} 21% 17%`,
            "--secondary": `${hue} 19% 88%`,
            "--secondary-foreground": `${hue} 28% 16%`,
        } as CSSProperties,
    }
}