import { type CSSProperties } from "react";

export function floconMono(hue: number) {
    return {
        dark: {
            "--accent": `${hue} 0% 90%`,
            "--accent-foreground": `${hue} 0% 4%`,
            "--background": `${hue} 0% 6%`,
            "--border": `${hue} 0% 16%`,
            "--card": `${hue} 0% 8%`,
            "--card-foreground": `${hue} 0% 90%`,
            "--foreground": `${hue} 0% 90%`,
            "--input": `${hue} 0% 20%`,
            "--muted": `${hue} 0% 13%`,
            "--muted-foreground": `${hue} 0% 75%`,
            "--popover": `${hue} 0% 100%`,
            "--popover-foreground": `${hue} 0% 10%`,
            "--primary": `${hue} 0% 62%`,
            "--primary-foreground": `${hue} 0% 100%`,
            "--ring": `${hue} 0% 90%`,
            "--secondary": `${hue} 0% 10%`,
            "--secondary-foreground": `${hue} 0% 100%`,
        } as CSSProperties,
        light: {
            "--accent": `${hue} 0% 10%`,
            "--accent-foreground": `${hue} 0% 15%`,
            "--background": `${hue} 0% 99%`,
            "--border": `${hue} 0% 77%`,
            "--card": `${hue} 0% 99%`,
            "--card-foreground": `${hue} 0% 17%`,
            "--foreground": `${hue} 0% 16%`,
            "--input": `${hue} 0% 77%`,
            "--muted": `${hue} 0% 94%`,
            "--muted-foreground": `${hue} 0% 35%`,
            "--popover": `${hue} 0% 100%`,
            "--popover-foreground": `${hue} 0% 10%`,
            "--primary": `${hue} 0% 40%`,
            "--primary-foreground": `${hue} 0% 100%`,
            "--ring": `${hue} 0% 32%`,
            "--secondary": `${hue} 0% 93%`,
            "--secondary-foreground": `${hue} 0% 15%`,
        } as CSSProperties,
    }
}

export function charmMono(hue: number) {
    return {
        dark: {
            "--accent": `${hue} 0% 14%`,
            "--accent-foreground": `${hue} 0% 98%`,
            "--background": `${hue} 0% 3%`,
            "--border": `${hue} 0% 9%`,
            "--card": `${hue} 0% 5%`,
            "--card-foreground": `${hue} 0% 97%`,
            "--foreground": `${hue} 0% 96%`,
            "--input": `${hue} 0% 13%`,
            "--muted": `${hue} 0% 15%`,
            "--muted-foreground": `${hue} 0% 64%`,
            "--popover": `${hue} 0% 3%`,
            "--popover-foreground": `${hue} 0% 98%`,
            "--primary": `${hue} 0% 87%`,
            "--primary-foreground": `${hue} 0% 10%`,
            "--ring": `${hue} 0% 83%`,
            "--secondary": `${hue} 0% 13%`,
            "--secondary-foreground": `${hue} 0% 95%`,
        } as CSSProperties,
        light: {
            "--accent": `${hue} 0% 92%`,
            "--accent-foreground": `${hue} 0% 7%`,
            "--background": `${hue} 0% 99%`,
            "--border": `${hue} 0% 92%`,
            "--card": `${hue} 0% 100%`,
            "--card-foreground": `${hue} 0% 7%`,
            "--foreground": `${hue} 0% 7%`,
            "--input": `${hue} 0% 92%`,
            "--muted": `${hue} 0% 90%`,
            "--muted-foreground": `${hue} 0% 30%`,
            "--popover": `${hue} 0% 90%`,
            "--popover-foreground": `${hue} 0% 7%`,
            "--primary": `${hue} 0% 20%`,
            "--primary-foreground": `${hue} 0% 96%`,
            "--ring": `${hue} 0% 3%`,
            "--secondary": `${hue} 0% 90%`,
            "--secondary-foreground": `${hue} 0% 5%`,
        } as CSSProperties,
    }
}

export function eclipseMono(hue: number) {
    return {
        dark: {
            "--accent": `${hue} 0% 17%`,
            "--accent-foreground": `${hue} 0% 100%`,
            "--background": `${hue} 0% 1%`,
            "--border": `${hue} 0% 23%`,
            "--card": `${hue} 0% 3%`,
            "--card-foreground": `${hue} 0% 100%`,
            "--foreground": `${hue} 0% 100%`,
            "--input": `${hue} 0% 23%`,
            "--muted": `${hue} 0% 8%`,
            "--muted-foreground": `${hue} 0% 52%`,
            "--popover": `${hue} 0% 1%`,
            "--popover-foreground": `${hue} 0% 100%`,
            "--primary": `${hue} 0% 92%`,
            "--primary-foreground": `${hue} 0% 0%`,
            "--ring": `${hue} 0% 90%`,
            "--secondary": `${hue} 0% 14%`,
            "--secondary-foreground": `${hue} 0% 100%`,
        } as CSSProperties,
        light: {
            "--accent": `${hue} 0% 88%`,
            "--accent-foreground": `${hue} 0% 0%`,
            "--background": `${hue} 0% 99%`,
            "--border": `${hue} 0% 62%`,
            "--card": `${hue} 0% 100%`,
            "--card-foreground": `${hue} 0% 0%`,
            "--foreground": `${hue} 0% 0%`,
            "--input": `${hue} 0% 60%`,
            "--muted": `${hue} 0% 93%`,
            "--muted-foreground": `${hue} 0% 49%`,
            "--popover": `${hue} 0% 99%`,
            "--popover-foreground": `${hue} 0% 0%`,
            "--primary": `${hue} 0% 9%`,
            "--primary-foreground": `${hue} 0% 100%`,
            "--ring": `${hue} 0% 11%`,
            "--secondary": `${hue} 0% 92%`,
            "--secondary-foreground": `${hue} 0% 9%`,
        } as CSSProperties,
    }
}

export function oasisMono(hue: number) {
    return {
        dark: {
            "--accent": `${hue} 0% 24%`,
            "--accent-foreground": `${hue} 0% 95%`,
            "--background": `${hue} 0% 4%`,
            "--border": `${hue} 0% 16%`,
            "--card": `${hue} 0% 8%`,
            "--card-foreground": `${hue} 0% 96%`,
            "--foreground": `${hue} 0% 90%`,
            "--input": `${hue} 0% 16%`,
            "--muted": `${hue} 0% 9%`,
            "--muted-foreground": `${hue} 0% 56%`,
            "--popover": `${hue} 0% 10%`,
            "--popover-foreground": `${hue} 0% 98%`,
            "--primary": `${hue} 0% 37%`,
            "--primary-foreground": `${hue} 0% 96%`,
            "--ring": `${hue} 0% 17%`,
            "--secondary": `${hue} 0% 10%`,
            "--secondary-foreground": `${hue} 0% 90%`,
        } as CSSProperties,
        light: {
            "--accent": `${hue} 0% 88%`,
            "--accent-foreground": `${hue} 0% 14%`,
            "--background": `${hue} 0% 97%`,
            "--border": `${hue} 0% 87%`,
            "--card": `${hue} 0% 99%`,
            "--card-foreground": `${hue} 0% 15%`,
            "--foreground": `${hue} 0% 15%`,
            "--input": `${hue} 0% 87%`,
            "--muted": `${hue} 0% 87%`,
            "--muted-foreground": `${hue} 0% 56%`,
            "--popover": `${hue} 0% 99%`,
            "--popover-foreground": `${hue} 0% 10%`,
            "--primary": `${hue} 0% 37%`,
            "--primary-foreground": `${hue} 0% 96%`,
            "--ring": `${hue} 0% 17%`,
            "--secondary": `${hue} 0% 88%`,
            "--secondary-foreground": `${hue} 0% 16%`,
        } as CSSProperties,
    }
}